<?php

namespace UserBundle\Repository;

use Doctrine\ORM\EntityRepository;
use UserBundle\Entity\Card;

/**
 * CardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardRepository extends EntityRepository
{
    /**
     * @return null|Card|object
     */
    public function findOneWithNoUser()
    {
        return $this->findOneBy(['user' => null]);
    }
}
