<?php

namespace UserBundle\Repository;

use Doctrine\ORM\EntityRepository;
use UserBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * @param $username
     * @return User|null
     */
    public function findByUsernameOrCard($username)
    {
        return $this->createQueryBuilder('u')
            ->leftJoin("u.card", "card")
            ->where("UPPER(u.username) = :username ")
            ->orWhere("card.uuid = :username")
            ->setParameter('username', strtoupper($username))
            ->getQuery()
            ->getOneOrNullResult();
    }
}
